-- ============================================================
-- MIGRACIÓN: Acción Terapéutica en productos
-- Hospital Dr. Armando Cima
--
-- CÓMO EJECUTAR EN phpMyAdmin:
--   1. Seleccioná la base 'stock_control' en el panel izquierdo
--   2. Pestaña 'SQL'
--   3. Pegá TODO el contenido de este archivo
--   4. Clic en 'Continuar'
-- ============================================================

USE stock_control;

-- Agregar columna
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS therapeutic_action VARCHAR(150) DEFAULT NULL AFTER description;

-- ── Insumos: ampollas inyectables ────────────────────────────────────
UPDATE products SET therapeutic_action = 'Antiarrítmico'                     WHERE code = 'INS-140';
UPDATE products SET therapeutic_action = 'Vasopresivo / Broncodilatador'      WHERE code = 'INS-141';
UPDATE products SET therapeutic_action = 'Disolvente / Vehículo'              WHERE code = 'INS-142';
UPDATE products SET therapeutic_action = 'Broncodilatador xantínico'          WHERE code = 'INS-143';
UPDATE products SET therapeutic_action = 'Antiarrítmico'                      WHERE code = 'INS-144';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'INS-145';
UPDATE products SET therapeutic_action = 'Anticolinérgico'                    WHERE code = 'INS-146';
UPDATE products SET therapeutic_action = 'Vitamínico (B1, B2, B5, B6)'        WHERE code = 'INS-147';
UPDATE products SET therapeutic_action = 'Corticoide'                         WHERE code = 'INS-148';
UPDATE products SET therapeutic_action = 'Antibiótico cefalosporina'          WHERE code = 'INS-149';
UPDATE products SET therapeutic_action = 'Antibiótico quinolona'              WHERE code = 'INS-150';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'INS-151';
UPDATE products SET therapeutic_action = 'Electrolito'                        WHERE code = 'INS-152';
UPDATE products SET therapeutic_action = 'Electrolito'                        WHERE code = 'INS-153';
UPDATE products SET therapeutic_action = 'Corticoide'                         WHERE code = 'INS-154';
UPDATE products SET therapeutic_action = 'Ansiolítico / Anticonvulsivo'       WHERE code = 'INS-155';
UPDATE products SET therapeutic_action = 'AINE / Analgésico'                  WHERE code = 'INS-156';
UPDATE products SET therapeutic_action = 'Antihistamínico'                    WHERE code = 'INS-157';
UPDATE products SET therapeutic_action = 'Glucósido cardíaco'                 WHERE code = 'INS-158';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'INS-159';
UPDATE products SET therapeutic_action = 'Vasopresivo / Inotrópico'           WHERE code = 'INS-160';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'INS-161';
UPDATE products SET therapeutic_action = 'Antagonista benzodiazepinas'        WHERE code = 'INS-162';
UPDATE products SET therapeutic_action = 'Diurético'                          WHERE code = 'INS-163';
UPDATE products SET therapeutic_action = 'Anticoagulante'                     WHERE code = 'INS-164';
UPDATE products SET therapeutic_action = 'Corticoide'                         WHERE code = 'INS-165';
UPDATE products SET therapeutic_action = 'Corticoide'                         WHERE code = 'INS-166';
UPDATE products SET therapeutic_action = 'Antiespasmódico / Analgésico'       WHERE code = 'INS-167';
UPDATE products SET therapeutic_action = 'Antiespasmódico'                    WHERE code = 'INS-168';
UPDATE products SET therapeutic_action = 'AINE / Analgésico'                  WHERE code = 'INS-169';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Betabloqueante'  WHERE code = 'INS-170';
UPDATE products SET therapeutic_action = 'Antipsicótico / Sedante'            WHERE code = 'INS-171';
UPDATE products SET therapeutic_action = 'Anestésico local'                   WHERE code = 'INS-172';
UPDATE products SET therapeutic_action = 'Anestésico local'                   WHERE code = 'INS-173';
UPDATE products SET therapeutic_action = 'Ansiolítico / Anticonvulsivo'       WHERE code = 'INS-174';
UPDATE products SET therapeutic_action = 'Antiemético / Procinético'          WHERE code = 'INS-175';
UPDATE products SET therapeutic_action = 'Sedante / Ansiolítico'              WHERE code = 'INS-176';
UPDATE products SET therapeutic_action = 'Analgésico opioide'                 WHERE code = 'INS-177';
UPDATE products SET therapeutic_action = 'Antagonista opioide'                WHERE code = 'INS-178';
UPDATE products SET therapeutic_action = 'Vasodilatador / Antiangionoso'      WHERE code = 'INS-179';
UPDATE products SET therapeutic_action = 'Vasopresivo'                        WHERE code = 'INS-180';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'INS-181';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'INS-182';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'INS-183';
UPDATE products SET therapeutic_action = 'Antiulceroso / Antisecretor H2'     WHERE code = 'INS-184';
UPDATE products SET therapeutic_action = 'Suplemento energético'              WHERE code = 'INS-185';
UPDATE products SET therapeutic_action = 'Antidiabético / Insulina'           WHERE code = 'INS-189';
UPDATE products SET therapeutic_action = 'Antidiabético / Insulina'           WHERE code = 'INS-190';
UPDATE products SET therapeutic_action = 'Diagnóstico'                        WHERE code = 'INS-191';

-- ── Medicación fuera de Remediar ─────────────────────────────────────
UPDATE products SET therapeutic_action = 'Vitamínico / Hematínico'            WHERE code = 'MED-001';
UPDATE products SET therapeutic_action = 'Vitamínico / Hematínico'            WHERE code = 'MED-002';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'MED-003';
UPDATE products SET therapeutic_action = 'Dispositivo inhalador'              WHERE code = 'MED-004';
UPDATE products SET therapeutic_action = 'Dispositivo inhalador'              WHERE code = 'MED-005';
UPDATE products SET therapeutic_action = 'Mucolítico / Expectorante'          WHERE code = 'MED-006';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Calcioantagonista' WHERE code = 'MED-007';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-008';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-009';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-010';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-011';
UPDATE products SET therapeutic_action = 'Antiagregante plaquetario / AINE'   WHERE code = 'MED-012';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Betabloqueante'  WHERE code = 'MED-013';
UPDATE products SET therapeutic_action = 'Hipolipemiante / Estatina'          WHERE code = 'MED-014';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-015';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-016';
UPDATE products SET therapeutic_action = 'Corticoide tópico'                  WHERE code = 'MED-017';
UPDATE products SET therapeutic_action = 'Corticoide tópico'                  WHERE code = 'MED-018';
UPDATE products SET therapeutic_action = 'Corticoide'                         WHERE code = 'MED-019';
UPDATE products SET therapeutic_action = 'Mucolítico / Expectorante'          WHERE code = 'MED-020';
UPDATE products SET therapeutic_action = 'Broncodilatador anticolinérgico'    WHERE code = 'MED-021';
UPDATE products SET therapeutic_action = 'Broncodilatador anticolinérgico'    WHERE code = 'MED-022';
UPDATE products SET therapeutic_action = 'Corticoide inhalado / Antiasmático' WHERE code = 'MED-023';
UPDATE products SET therapeutic_action = 'Corticoide inhalado / Antiasmático' WHERE code = 'MED-024';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'MED-025';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'MED-026';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Betabloqueante'  WHERE code = 'MED-027';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-028';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-029';
UPDATE products SET therapeutic_action = 'Antibiótico quinolona'              WHERE code = 'MED-030';
UPDATE products SET therapeutic_action = 'Antibiótico + Anestésico + Corticoide ótico' WHERE code = 'MED-031';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-032';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-033';
UPDATE products SET therapeutic_action = 'Ansiolítico / Antiepiléptico'       WHERE code = 'MED-034';
UPDATE products SET therapeutic_action = 'Ansiolítico / Antiepiléptico'       WHERE code = 'MED-035';
UPDATE products SET therapeutic_action = 'Antidiarreico / Protector gástrico' WHERE code = 'MED-036';
UPDATE products SET therapeutic_action = 'AINE / Analgésico'                  WHERE code = 'MED-037';
UPDATE products SET therapeutic_action = 'Antihistamínico'                    WHERE code = 'MED-038';
UPDATE products SET therapeutic_action = 'Antihistamínico'                    WHERE code = 'MED-039';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'MED-040';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'MED-041';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'MED-042';
UPDATE products SET therapeutic_action = 'Antihipertensivo / IECA'            WHERE code = 'MED-043';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'MED-044';
UPDATE products SET therapeutic_action = 'Hipolipemiante / Fibrato'           WHERE code = 'MED-045';
UPDATE products SET therapeutic_action = 'Antifúngico'                        WHERE code = 'MED-046';
UPDATE products SET therapeutic_action = 'Diurético'                          WHERE code = 'MED-047';
UPDATE products SET therapeutic_action = 'Antidiabético / Sulfonilurea'       WHERE code = 'MED-048';
UPDATE products SET therapeutic_action = 'Diurético / Antihipertensivo'       WHERE code = 'MED-049';
UPDATE products SET therapeutic_action = 'Hematínico / Antianémico'           WHERE code = 'MED-050';
UPDATE products SET therapeutic_action = 'Antiespasmódico'                    WHERE code = 'MED-051';
UPDATE products SET therapeutic_action = 'AINE / Analgésico / Antipirético'   WHERE code = 'MED-052';
UPDATE products SET therapeutic_action = 'AINE / Analgésico / Antipirético'   WHERE code = 'MED-053';
UPDATE products SET therapeutic_action = 'AINE / Analgésico'                  WHERE code = 'MED-054';
UPDATE products SET therapeutic_action = 'Hormona tiroidea'                   WHERE code = 'MED-055';
UPDATE products SET therapeutic_action = 'Hormona tiroidea'                   WHERE code = 'MED-056';
UPDATE products SET therapeutic_action = 'Antihistamínico'                    WHERE code = 'MED-057';
UPDATE products SET therapeutic_action = 'Antihistamínico'                    WHERE code = 'MED-058';
UPDATE products SET therapeutic_action = 'Ansiolítico / Benzodiazepina'       WHERE code = 'MED-059';
UPDATE products SET therapeutic_action = 'Antidiarreico'                      WHERE code = 'MED-060';
UPDATE products SET therapeutic_action = 'Antihipertensivo / ARA II'          WHERE code = 'MED-061';
UPDATE products SET therapeutic_action = 'Antihipertensivo / ARA II'          WHERE code = 'MED-062';
UPDATE products SET therapeutic_action = 'Antiparasitario'                    WHERE code = 'MED-063';
UPDATE products SET therapeutic_action = 'Antiparasitario'                    WHERE code = 'MED-064';
UPDATE products SET therapeutic_action = 'Antihipertensivo'                   WHERE code = 'MED-065';
UPDATE products SET therapeutic_action = 'Antidiabético / Biguanida'          WHERE code = 'MED-066';
UPDATE products SET therapeutic_action = 'Antidiabético / Biguanida'          WHERE code = 'MED-067';
UPDATE products SET therapeutic_action = 'Antiemético / Procinético'          WHERE code = 'MED-068';
UPDATE products SET therapeutic_action = 'Antiemético / Procinético'          WHERE code = 'MED-069';
UPDATE products SET therapeutic_action = 'Antibiótico / Antiprotozoario'      WHERE code = 'MED-070';
UPDATE products SET therapeutic_action = 'Antibiótico / Antiprotozoario'      WHERE code = 'MED-071';
UPDATE products SET therapeutic_action = 'Antifúngico'                        WHERE code = 'MED-072';
UPDATE products SET therapeutic_action = 'Antibiótico quinolona'              WHERE code = 'MED-073';
UPDATE products SET therapeutic_action = 'Inhibidor bomba de protones'        WHERE code = 'MED-074';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'MED-075';
UPDATE products SET therapeutic_action = 'Antiparasitario (escabicida)'       WHERE code = 'MED-076';
UPDATE products SET therapeutic_action = 'Corticoide sistémico'               WHERE code = 'MED-077';
UPDATE products SET therapeutic_action = 'Corticoide sistémico'               WHERE code = 'MED-078';
UPDATE products SET therapeutic_action = 'Antipsicótico'                      WHERE code = 'MED-079';
UPDATE products SET therapeutic_action = 'Broncodilatador / Agonista B2'      WHERE code = 'MED-080';
UPDATE products SET therapeutic_action = 'Broncodilatador / Agonista B2'      WHERE code = 'MED-081';
UPDATE products SET therapeutic_action = 'Rehidratación oral'                 WHERE code = 'MED-082';
UPDATE products SET therapeutic_action = 'Antidepresivo / ISRS'               WHERE code = 'MED-083';
UPDATE products SET therapeutic_action = 'Antibiótico oftálmico'              WHERE code = 'MED-084';
UPDATE products SET therapeutic_action = 'Antibiótico + Corticoide oftálmico' WHERE code = 'MED-085';
UPDATE products SET therapeutic_action = 'Anestésico oftálmico'               WHERE code = 'MED-086';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-087';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-088';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-089';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-090';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Calcioantagonista' WHERE code = 'MED-091';
UPDATE products SET therapeutic_action = 'Corticoide inhalado / Antiasmático' WHERE code = 'MED-092';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-093';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'MED-094';
UPDATE products SET therapeutic_action = 'Antibiótico quinolona'              WHERE code = 'MED-095';
UPDATE products SET therapeutic_action = 'Antihipertensivo / IECA'            WHERE code = 'MED-096';
UPDATE products SET therapeutic_action = 'Diurético'                          WHERE code = 'MED-097';
UPDATE products SET therapeutic_action = 'AINE / Analgésico / Antipirético'   WHERE code = 'MED-098';
UPDATE products SET therapeutic_action = 'AINE / Analgésico / Antipirético'   WHERE code = 'MED-099';
UPDATE products SET therapeutic_action = 'Antihistamínico'                    WHERE code = 'MED-100';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'MED-101';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'MED-102';
UPDATE products SET therapeutic_action = 'Broncodilatador / Agonista B2'      WHERE code = 'MED-103';
UPDATE products SET therapeutic_action = 'Rehidratación oral'                 WHERE code = 'MED-104';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'MED-105';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'MED-106';
UPDATE products SET therapeutic_action = 'AINE / Analgésico / Antipirético'   WHERE code = 'MED-107';
UPDATE products SET therapeutic_action = 'AINE / Analgésico / Antipirético'   WHERE code = 'MED-108';

-- ── Remediar ─────────────────────────────────────────────────────────
UPDATE products SET therapeutic_action = 'Antiviral'                          WHERE code = 'REM-802';
UPDATE products SET therapeutic_action = 'Vitamínico / Hematínico'            WHERE code = 'REM-117';
UPDATE products SET therapeutic_action = 'Antibiótico tópico'                 WHERE code = 'REM-003';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'REM-004';
UPDATE products SET therapeutic_action = 'Antigotoso / Hipouricemiante'       WHERE code = 'REM-803';
UPDATE products SET therapeutic_action = 'Antiarrítmico'                      WHERE code = 'REM-006';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Calcioantagonista' WHERE code = 'REM-007';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Calcioantagonista' WHERE code = 'REM-008';
UPDATE products SET therapeutic_action = 'Antihipertensivo combinado'         WHERE code = 'REM-009';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-010';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-011';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-103';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-104';
UPDATE products SET therapeutic_action = 'Antiagregante plaquetario'          WHERE code = 'REM-014';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Betabloqueante'  WHERE code = 'REM-015';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-016';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-017';
UPDATE products SET therapeutic_action = 'Corticoide tópico'                  WHERE code = 'REM-018';
UPDATE products SET therapeutic_action = 'Corticoide'                         WHERE code = 'REM-019';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Betabloqueante'  WHERE code = 'REM-020';
UPDATE products SET therapeutic_action = 'Corticoide inhalado / Antiasmático' WHERE code = 'REM-021';
UPDATE products SET therapeutic_action = 'Corticoide + Broncodilatador'       WHERE code = 'REM-022';
UPDATE products SET therapeutic_action = 'Suplemento mineral'                 WHERE code = 'REM-023';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'REM-024';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Betabloqueante'  WHERE code = 'REM-025';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Betabloqueante'  WHERE code = 'REM-026';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-027';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-028';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-029';
UPDATE products SET therapeutic_action = 'Antibiótico cefalosporina'          WHERE code = 'REM-030';
UPDATE products SET therapeutic_action = 'Antibiótico quinolona'              WHERE code = 'REM-031';
UPDATE products SET therapeutic_action = 'Antibiótico + Corticoide ótico'     WHERE code = 'REM-032';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-033';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-034';
UPDATE products SET therapeutic_action = 'Antibiótico + Antifúngico vaginal'  WHERE code = 'REM-035';
UPDATE products SET therapeutic_action = 'Corticoide'                         WHERE code = 'REM-036';
UPDATE products SET therapeutic_action = 'Antihistamínico'                    WHERE code = 'REM-037';
UPDATE products SET therapeutic_action = 'Antihistamínico'                    WHERE code = 'REM-038';
UPDATE products SET therapeutic_action = 'Glucósido cardíaco / Antiarrítmico' WHERE code = 'REM-039';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'REM-040';
UPDATE products SET therapeutic_action = 'Antihipertensivo / IECA'            WHERE code = 'REM-041';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-042';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-043';
UPDATE products SET therapeutic_action = 'Antibiótico oftálmico'              WHERE code = 'REM-044';
UPDATE products SET therapeutic_action = 'Dispositivo inhalador'              WHERE code = 'REM-045';
UPDATE products SET therapeutic_action = 'Diurético ahorrador de potasio'     WHERE code = 'REM-046';
UPDATE products SET therapeutic_action = 'Cicatrizante / Antiinflamatorio tópico' WHERE code = 'REM-047';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'REM-048';
UPDATE products SET therapeutic_action = 'Hipolipemiante / Fibrato'           WHERE code = 'REM-049';
UPDATE products SET therapeutic_action = 'Antifúngico'                        WHERE code = 'REM-050';
UPDATE products SET therapeutic_action = 'Antibiótico / Antiprotozoario'      WHERE code = 'REM-051';
UPDATE products SET therapeutic_action = 'Diurético'                          WHERE code = 'REM-052';
UPDATE products SET therapeutic_action = 'Antibiótico tópico'                 WHERE code = 'REM-053';
UPDATE products SET therapeutic_action = 'Antibiótico oftálmico'              WHERE code = 'REM-054';
UPDATE products SET therapeutic_action = 'Antidiabético / Sulfonilurea'       WHERE code = 'REM-055';
UPDATE products SET therapeutic_action = 'Antidiabético / Sulfonilurea'       WHERE code = 'REM-056';
UPDATE products SET therapeutic_action = 'Diurético / Antihipertensivo'       WHERE code = 'REM-057';
UPDATE products SET therapeutic_action = 'Hematínico / Antianémico'           WHERE code = 'REM-058';
UPDATE products SET therapeutic_action = 'Hematínico / Antianémico'           WHERE code = 'REM-059';
UPDATE products SET therapeutic_action = 'Antiespasmódico'                    WHERE code = 'REM-060';
UPDATE products SET therapeutic_action = 'AINE / Analgésico / Antipirético'   WHERE code = 'REM-061';
UPDATE products SET therapeutic_action = 'AINE / Analgésico / Antipirético'   WHERE code = 'REM-062';
UPDATE products SET therapeutic_action = 'Broncodilatador anticolinérgico'    WHERE code = 'REM-063';
UPDATE products SET therapeutic_action = 'Antiparasitario'                    WHERE code = 'REM-064';
UPDATE products SET therapeutic_action = 'Antihipertensivo / Betabloqueante'  WHERE code = 'REM-065';
UPDATE products SET therapeutic_action = 'Antiparkinsónico'                   WHERE code = 'REM-066';
UPDATE products SET therapeutic_action = 'Hormona tiroidea'                   WHERE code = 'REM-067';
UPDATE products SET therapeutic_action = 'Hormona tiroidea'                   WHERE code = 'REM-068';
UPDATE products SET therapeutic_action = 'Antidiarreico'                      WHERE code = 'REM-069';
UPDATE products SET therapeutic_action = 'Antihistamínico'                    WHERE code = 'REM-070';
UPDATE products SET therapeutic_action = 'Antihistamínico'                    WHERE code = 'REM-071';
UPDATE products SET therapeutic_action = 'Antihipertensivo / ARA II'          WHERE code = 'REM-072';
UPDATE products SET therapeutic_action = 'Antihipertensivo / ARA II'          WHERE code = 'REM-073';
UPDATE products SET therapeutic_action = 'Antiparasitario'                    WHERE code = 'REM-074';
UPDATE products SET therapeutic_action = 'Antiparasitario'                    WHERE code = 'REM-075';
UPDATE products SET therapeutic_action = 'Corticoide sistémico'               WHERE code = 'REM-076';
UPDATE products SET therapeutic_action = 'Corticoide sistémico'               WHERE code = 'REM-077';
UPDATE products SET therapeutic_action = 'Antidiabético / Biguanida'          WHERE code = 'REM-078';
UPDATE products SET therapeutic_action = 'Antidiabético / Biguanida'          WHERE code = 'REM-079';
UPDATE products SET therapeutic_action = 'Antidiabético / Biguanida'          WHERE code = 'REM-080';
UPDATE products SET therapeutic_action = 'Antihipertensivo'                   WHERE code = 'REM-081';
UPDATE products SET therapeutic_action = 'Antiemético / Procinético'          WHERE code = 'REM-082';
UPDATE products SET therapeutic_action = 'Antiemético / Procinético'          WHERE code = 'REM-083';
UPDATE products SET therapeutic_action = 'Antibiótico / Antiprotozoario'      WHERE code = 'REM-084';
UPDATE products SET therapeutic_action = 'Antibiótico / Antiprotozoario vaginal' WHERE code = 'REM-085';
UPDATE products SET therapeutic_action = 'Antibiótico / Antiprotozoario'      WHERE code = 'REM-086';
UPDATE products SET therapeutic_action = 'Antifúngico tópico'                 WHERE code = 'REM-087';
UPDATE products SET therapeutic_action = 'Antifúngico vaginal'                WHERE code = 'REM-088';
UPDATE products SET therapeutic_action = 'Antifúngico'                        WHERE code = 'REM-089';
UPDATE products SET therapeutic_action = 'Antibiótico urinario'               WHERE code = 'REM-090';
UPDATE products SET therapeutic_action = 'Antibiótico quinolona'              WHERE code = 'REM-091';
UPDATE products SET therapeutic_action = 'Inhibidor bomba de protones'        WHERE code = 'REM-092';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'REM-093';
UPDATE products SET therapeutic_action = 'Analgésico / Antipirético'          WHERE code = 'REM-094';
UPDATE products SET therapeutic_action = 'Antiparasitario (pediculosis)'      WHERE code = 'REM-095';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-096';
UPDATE products SET therapeutic_action = 'Antiparasitario (escabicida)'       WHERE code = 'REM-305';
UPDATE products SET therapeutic_action = 'Antiparasitario (pediculicida)'     WHERE code = 'REM-098';
UPDATE products SET therapeutic_action = 'Vitamínico / Suplemento'            WHERE code = 'REM-099';
UPDATE products SET therapeutic_action = 'Hipolipemiante / Estatina'          WHERE code = 'REM-366';
UPDATE products SET therapeutic_action = 'Broncodilatador / Agonista B2'      WHERE code = 'REM-101';
UPDATE products SET therapeutic_action = 'Broncodilatador / Agonista B2'      WHERE code = 'REM-102';
UPDATE products SET therapeutic_action = 'Rehidratación oral'                 WHERE code = 'REM-103';
UPDATE products SET therapeutic_action = 'Hipolipemiante / Estatina'          WHERE code = 'REM-104';
UPDATE products SET therapeutic_action = 'Antibiótico tópico / Cicatrizante'  WHERE code = 'REM-505';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-763';
UPDATE products SET therapeutic_action = 'Antibiótico'                        WHERE code = 'REM-107';
UPDATE products SET therapeutic_action = 'Antibiótico oftálmico'              WHERE code = 'REM-464';
UPDATE products SET therapeutic_action = 'Antiepiléptico'                     WHERE code = 'REM-108';
UPDATE products SET therapeutic_action = 'Vitamínico / Cicatrizante'          WHERE code = 'REM-110';
UPDATE products SET therapeutic_action = 'Vitamínico / Suplemento'            WHERE code = 'REM-111';
UPDATE products SET therapeutic_action = 'Anticolinérgico / Antiparkinsónico' WHERE code = 'REM-431';
UPDATE products SET therapeutic_action = 'Ansiolítico / Anticonvulsivo'       WHERE code = 'REM-432';
UPDATE products SET therapeutic_action = 'Antidepresivo / ISRS'               WHERE code = 'REM-435';
UPDATE products SET therapeutic_action = 'Antipsicótico'                      WHERE code = 'REM-474';
UPDATE products SET therapeutic_action = 'Antipsicótico'                      WHERE code = 'REM-467';
UPDATE products SET therapeutic_action = 'Antipsicótico'                      WHERE code = 'REM-433';
UPDATE products SET therapeutic_action = 'Antipsicótico'                      WHERE code = 'REM-434';
UPDATE products SET therapeutic_action = 'Antidepresivo / ISRS'               WHERE code = 'REM-375';

SELECT CONCAT('Acción terapéutica cargada en ', COUNT(*), ' productos') AS resultado
FROM products WHERE therapeutic_action IS NOT NULL;
